### ISSUE TITLE
go get github.com/HewlettPackard/lustre_exporter Does not work with go1.16.3.

### ISSUE THREAD

**Issue by arshad512** [HewlettPackard/lustre_exporter#150]
Doing 'go get' on latest (go1.16.3) Fails 
```
$ go get github.com/HewlettPackard/lustre_exporter
# github.com/HewlettPackard/lustre_exporter
pkg/mod/github.com/!hewlett!packard/lustre_exporter@v2.0.0+incompatible/lustre_exporter.go:153:28: undefined: prometheus.InstrumentHandler
```
Version
```
$ cat /usr/local/go/VERSION 
go1.16.3[root@centos79 go]# 
```
However, droping a version down and retrying it passes and works on (go1.15.11).

It most likely looks like the go1.16.3 breaks 'lustre_exporter'. 

Additional Info:
```
$ uname -a
Linux centos79 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```

**Comment by gabrieleiannetti** [comment]
Hi,  
this fork is active and working with go1.17.5:  
https://github.com/GSI-HPC/lustre_exporter

**Comment by arshad512** [comment]
Hi,
Thanks for the update. As I mentioned in by bug report it also did work with (go1.15.11) at the time. Only with the latest (at that time it was (go1.16.3)) it did not work. I have not tried out with go1.17.5 yet, I know it worked for 15.11 and as you mentioned it works for 17.5. It does not work for 16.3 only.  Something that should be looked into?

**Comment by gabrieleiannetti** [comment]
Hi,  
as I said, we are running a fork and that was tested successfully with 1.17.5.  
It might also be running with lower/higher version of go...  
If you strongly rely on a specific golang version, you have to check it out.  
I would recommend building the project with the tested version.

**Comment by arshad512** [comment]
Hi,
>https://github.com/GSI-HPC/lustre_exporter

I failed to mentioned that I used this fork as base. What failed was (HewlettPackard/lustre_exporter). The project does not depend upon golang version. It was just that at that time the latest was 16.3 and  HP/lustre_exporter (go get) failed to work. Thanks!

**Comment by gabrieleiannetti** [comment]
You welcome!  
This project is not active since 2019...

**Comment by arshad512** [comment]
> This project is not active since 2019..

Yes. However, this had more latest commits than HP's

**Comment by gabrieleiannetti** [comment]
Yes, the HP project has not been updated since 2019.  
As I said, https://github.com/GSI-HPC/lustre_exporter is an active fork.
